<!-- Slideshow container -->
<div class="slideshow-container">

    <!-- Full-width images with number and caption text -->
    <div class="mySlides fade">
        <div class="w-1/2 mx-auto text-center">
            <img class="mx-auto" src="/icon/small-slider/001-printing.svg" width="136" height="136"/>
            <div class="mt-6 mb-2 text-blue-300 font-bold">Printer:</div>
            <p class="w-max-s md:w-max-xs">
	    Print from the comfort of your sofa or even on the go? Great! The manufacturer is also happy. After
all, he gets your printed files.
            </p>
        </div>
    </div>

    <div class="mySlides fade">
        <div class="w-1/2 mx-auto text-center">
            <img class="mx-auto" src="/icon/small-slider/002-vaccum-cleaner.svg" width="136" height="136"/>
            <div class="mt-6 mb-2 text-blue-300 font-bold">Robot vacuum cleaners:</div>
            <p class="w-max-s md:w-max-xs">
	    Robot vacuum cleaners create maps of the home to navigate better. Who else gets the maps? Guess
right: the manufacturer and highest bidder.
            </p>
        </div>
    </div>

    <div class="mySlides fade">
        <div class="w-1/2 mx-auto text-center">
            <img class="mx-auto" src="/icon/small-slider/003-radio.svg" width="136" height="136"/>
            <div class="mt-6 mb-2 text-blue-300 font-bold">Internet radio:</div>
            <p class="w-max-s md:w-max-xs">
	    This device also communicates via the internet and opens the door for attackers. In addition, your
musical taste is transmitted to the manufacturer.
	    </p>
        </div>
    </div>

    <div class="mySlides fade">
        <div class="w-1/2 mx-auto text-center">
            <img class="mx-auto" src="/icon/small-slider/005-smart-tv.svg" width="136" height="136"/>
            <div class="mt-6 mb-2 text-blue-300 font-bold">Smart TV:</div>
            <p class="w-max-s md:w-max-xs">
	    Over 50% of households in AT & DE own a Smart TV. Based on your favourite series, advertisers can
now show you personalised ads.
            </p>
        </div>
    </div>

    <div class="mySlides fade">
        <div class="w-1/2 mx-auto text-center">
            <img class="mx-auto" src="/icon/small-slider/004-speaker.svg" width="136" height="136"/>
            <div class="mt-6 mb-2 text-blue-300 font-bold">Voice assistent:</div>
            <p class="w-max-s md:w-max-xs">
	    Your voice assistant works permanently via the internet. Unfortunately, it hears absolutely
everything that happens in the room. How else is it supposed to listen to its wake-up commands?
            </p>
        </div>
    </div>

    <!-- Next and previous buttons -->
    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>
</div>
<br>

<!-- The dots/circles -->
<div style="text-align:center">
    <span class="dot" onclick="currentSlide(1)"></span>
    <span class="dot" onclick="currentSlide(2)"></span>
    <span class="dot" onclick="currentSlide(3)"></span>
    <span class="dot" onclick="currentSlide(4)"></span>
    <span class="dot" onclick="currentSlide(5)"></span>
</div>
